spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: Ankit@1234
    url: jdbc:mysql://127.0.0.1:3306/springbootsecurity
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: feec33f8fd1c79a3de8e
            client-secret: 4a3c0b0542f11a04d5a7ef0c65d53fd25d7012e6
            scope:
             - email
             - prfile
